name: Docker Build and Deploy

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .

      # Push the Docker image
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      # Deploy the Docker image (Optional, if you're using a cloud service like AWS, GCP, or Azure)
      - name: Deploy to Server
        run: |
          ssh user@server "docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest && \
          docker stop my-node-app || true && \
          docker run -d --name my-node-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest"
